# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image: gcc:6.1
image: rikorose/gcc-cmake

pipelines:
  default:
    - step:
        name: Build and run tests
        script: # Modify the commands below to build your repository.
          # version infos
          - gcc --version
          - cmake --version
          - mkdir build
          - cd build
          - cmake ..
          - make all_tests
          - ctest -V
