name: MicroMachine CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare environment
        run: |
          mkdir -p build
          cd build
      - name: Install termdbg dependencies
        run: |
          sudo apt-get install -y libncursesw5-dev
      - name: Configure
        working-directory: build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_LEGACY_INSTRUCTION_TESTS=ON ..
      - name: Build termdbg
        working-directory: build
        run: |
            make -j $(nproc) termdbg
      - name: Build micromachine tests
        working-directory: build
        run: |
          make -j $(nproc) all_tests all_legacy_tests
      - name: Run micromachine tests
        working-directory: build/micromachine-test
        run: |
          ctest --no-tests=error -V
      - name: Install SDK dependencies
        run: |
          sudo apt-get install -y binutils-arm-none-eabi gcc-arm-none-eabi
      - name: Build micromachine SDK
        working-directory: build
        run: |
          make -j $(nproc) sdk
      - name: Run micromachine SDK tests
        working-directory: build/sdk/test
        run: |
           ctest --no-tests=error -V
